apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: traefik
type: Opaque
stringData:
  email: kontakt@sciekipolskie.org
  apiKey: 0fed539978a6659ac3217a373ee54790b6e4b
  cloudflare: 1cCyQUkTa8eIWVoV2b4L9qSM0I7wsQ-t7uhovzlt
