version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: > 
      bash -c "python manage.py migrate && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9.7
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
    restart: on-failure
    logging:
      driver: none

  celery:
    hostname: celery
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A to_do_list worker -l info
    volumes:
      - ./:/app
    depends_on:
      - server
      - rabbitmq
