# Generated by Django 4.0.4 on 2022-05-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_task_title_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employees.employee'),
        ),
    ]
